### ISSUE TITLE
About this project

### ISSUE THREAD

**Issue by Dangwei-dw** [Ernestchenchen/SG-LRA#1]
It seems that your project is not very complete. Do you have any plans to continue open source in the future? Thank you.

**Comment by Ernestchenchen** [comment]
Of course! The complete training process code has not been released, as the paper is still in the submission stage. The focus of this work is to open source the largest existing dataset of scoliosis Cobb angle measurements, SpinalAI-2024. The dataset and its annotations are complete and we hope they can help in existing scientific research. After the paper is accepted, we will release the complete experimental code. If you need to reproduce the complete process now, you need to follow the steps in the Engine_data folder according to the code in the paper. [https://github.com/Ernestchenchen/Spinal-AI2024.git](url)

**Comment by Ernestchenchen** [comment]
> It seems that your project is not very complete. Do you have any plans to continue open source in the future? Thank you.
Of course! The complete training process code has not been released, as the paper is still in the submission stage. The focus of this work is to open source the largest existing dataset of scoliosis Cobb angle measurements, SpinalAI-2024. The dataset and its annotations are complete and we hope they can help in existing scientific research. After the paper is accepted, we will release the complete experimental code. If you need to reproduce the complete process now, you need to follow the steps in the Engine_data folder according to the code in the paper. [https://github.com/Ernestchenchen/Spinal-AI2024](url)

**Comment by Dangwei-dw** [comment]
Excellent project, looking forward to open source
